maintainers:
 - alexellis
 - martindekov

features:
 - comments
 - dco_ch eck

messages:
  - name: cool
    value: I am doing this just to test this functionality.
  - name: slack
    value: |
           --
           Join Slack to connect with the community
           https://docs.openfaas.com

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
